name: Deploy on AWS
on:
    push:
        branches:
            - main
jobs:
    AWS-Deploy:
        runs-on: self-hosted
        timeout-minutes: 20
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Make dynamic env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
                  envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
                  envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
                  envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
                  file: .env
                  fail_on_empty_file: true
            - name: Stop services and remove orphaned containers
              run: docker compose -f docker-compose.production.yml down --remove-orphans
            - name: Build and run services
              run: docker compose -f docker-compose.production.yml up --build
