name: Pull Request
on: [pull_request]
jobs:
    PullRequest:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Make dynamic env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_POSTGRES_USER: "postgres"
                  envkey_POSTGRES_PASSWORD: "postgres"
                  envkey_POSTGRES_DB: "tests"
                  envkey_DATABASE_URL: "postgresql://postgres:postgres@database-ci:5432/tests"
                  envkey_PRISMA_ENV: "test"
                  file_name: .env.test
            - name: Run tests
              run: docker-compose -f docker-compose.test.yml run api-ci npm run test:remote
